dailyhunt/buzz/urls.py
from django.urls import include, path
from .views import AddVideoView, VideosView

app_name='buzz'
urlpatterns=[
    path('create',AddVideoView.as_view(),name='create'),
    path('browse/',VideosView.as_view(),name='browse'),
    path('browse/<int:video_id>',VideosView.as_view(),name='see')
]

dailyhunt/dailyhunt/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import index
urlpatterns = [
    path('',index,name='home'),
    path('news/',include('news.urls',namespace='news')),
    path('buzz/',include('buzz.urls',namespace='buzz')),
    path('admin/', admin.site.urls),
]

dailyhunt/news/urls.py
from django.urls import include, path
from news import views

app_name='news'
urlpatterns = [
    path('create/', views.NewNewsView.as_view(), name='create'),
    path('browse/', views.NewsView.as_view(), name='browse'),
    path('browse/<int:news_id>/<slug:slug_part>/', views.NewsView.as_view(), name='see'),
    path('create_tag/', views.TagsView.as_view(), name='create_tag')
]

dailyhunt/buzz/models.py
from django.db import models
from news.models import Tags
# Create your models here.



class Video(models.Model):
    video_url=models.URLField(verbose_name='video_url',max_length=500)
    tags = models.ManyToManyField(Tags, related_name='videos')
    description = models.CharField(max_length=500)
    icon= models.CharField(max_length=500)
    thumbnail_url = models.URLField(name='thumbnail_url',max_length=4096,default='')
    title=models.CharField(max_length=255)

    def get_url(self):
        return self.video_url

dailyhunt/news/models.py
from django.db import models
import markdown
from django.utils.safestring import mark_safe
# Create your models here.

class Language(models.Model):
    name=models.CharField(max_length=50,blank=False)
    code= models.CharField(max_length=2,blank=False)

    def __str__(self):
        return "[{} - {}]".format(self.name, self.code)


class Tags(models.Model):
    name=models.CharField(max_length=50,blank=False, unique=True)
    language=models.ForeignKey(Language, related_name='tags', on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class News(models.Model):
    title=models.CharField(max_length=255, unique=False,blank=False)
    subtitle=models.CharField(max_length=100, null=True,blank=True)
    is_archived= models.BooleanField(default=False)
    created_at=models.DateTimeField(auto_now_add=True)
    publish_date=models.DateTimeField()
    language=models.ForeignKey(Language,related_name='news', on_delete= models.CASCADE)
    tags= models.ManyToManyField(Tags)
    content=models.TextField(verbose_name='Content',default='')

    def slugify(self):
        """
        Unsafe url characters: <,>,!,#,%,&,#,:,-,?,[,]{,},@
        """
        slug_title = self.title
        slug_title = str(slug_title).lower()
        unsafe_chars=['<','>','!','#','%','&','#',":",'-','?','[',']','{','}','@']
        for unsafe_char in unsafe_chars:
            slug_title = slug_title.replace(unsafe_char,"")
        parts = slug_title.split()
        if len(parts) >5:
            parts = parts[:5]
        
        slug = "-".join(parts)
        return slug
    
    def display(self):
        return mark_safe(markdown.markdown(str(self.content)))

dailyhunt/buzz/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['video_url','tags']

dailyhunt/news/forms.py
from django import forms
from .models import News, Tags, Language


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title','subtitle','content','publish_date','language','tags']

class TagForm(forms.ModelForm):
    class Meta:
        model = Tags
        fields = ['name','language']

dailyhunt/buzz/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from .forms import VideoForm
from .parse_video import get_video_info
from .models import Video
from news.models import Tags
from django.http import HttpResponseBadRequest
import logging

class AddVideoView(View):
    def post(self, request):
        form = VideoForm(request.POST)
        if form.is_valid():
            video = form.save(commit=False)
            url = video.video_url
            try:
                metaInfo = get_video_info(url)
                video.thumbnail_url = metaInfo.image_url
                video.title = metaInfo.title
                video.save()
                return redirect('home')
            except Exception as ex:
                metaInfo = None
                return HttpResponseBadRequest("unable to find the content at the url because "+str(ex))

    def get(self, request):
        videoForm = VideoForm()
        return render(request, 'buzz\create_video.html', {'form': videoForm})


class VideosView(View):
    def get(self, request, video_id=None):
        if video_id is not None:
            video = get_object_or_404(Video, pk=video_id)
            return render(request, 'buzz/see_video.html', {'video': video})
        else:
            videos = Video.objects.all()
            tags= Tags.objects.all()
            return render(request, 'buzz/browse_videos.html', {'videos': videos,'tags':tags})

dailyhunt/dailyhunt/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

dailyhunt/news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
# Create your views here.
from .models import News, Language,Tags
from .forms import NewsForm, TagForm



class NewNewsView(View):
    def post(self, request):
        form = NewsForm(request.POST)
        if form.is_valid():
            news = form.save(commit=False)
            news.save()
            return redirect('home')
        return render(request, 'news/create_news.html', {'form': form})

    def get(self, request):
        form = NewsForm()
        return render(request, 'news/create_news.html', {'form': form})


class NewsView(View):
    def get(self, request, news_id=None,slug_part=None):
        if news_id is not None:
            news = get_object_or_404(News, pk=news_id)
            return render(request, 'see_article.html', {'news': news})
        else:
            news = News.objects.all()
            tags= Tags.objects.all()
            return render(request, 'news/browse_news.html', {'news': news,'tags':tags})


class TagsView(View):
    def post(self, request):
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.save()
            return redirect('home')
        else:
            form = TagForm()
        return render(request, 'create_tag.html',{'form':form})
        
    def get(self, request):
        form = TagForm()
        return render(request, 'create_tag.html',{'form':form})

dailyhunt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
</head>

<body>
    <nav class="navbar navbar-expand-sm">
        <div class='container'>
            <a class='navbar-brand' href="{% url 'home'%}">News Hunt</a>
        </div>
    </nav>
    <div>

    </div>
    <div class='container body'>
       {% block content %}
        {%endblock%}
    </div>
    <footer>
        <div class="container">
                Copyright 2018
        </div>
        
    </footer>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

dailyhunt/templates/buzz/browse_videos.html
{% extends "base.html" %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/buzz.css' %}">
<h2>Videos</h6>
    <hr/>
    <div class='row'>
        <div class='col-md-3'>
            <ul class="list-group">
                {% for tag in tags %}
                <li class="list-group-item">
                    {{tag.name}}
                </li>
                {%endfor%}
            </ul>
        </div>
        <div class='col-md-9'>
            {% for video in videos %}
            <div class="videopost">
                <div class='thumbnail'>
                    <a href='{% url 'buzz:see' video.id %}'>
                        <img src="{{video.thumbnail_url}}" />
                       </a>
                </div>
                <div class='content'>
                    <div class="title"><a href='{% url 'buzz:see' video.id %}'>{{video.title}}</a></div>
                    <div class="subtitle"></div>
                </div>
            </div>
            {% endfor%}
        </div>
    </div>
    {% endblock content %}

dailyhunt/templates/buzz/create_video.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block content %} 
{% load static %}
<link rel="stylesheet" href="{% static 'css/simplemde.min.css'  %}" />
<script type="text/javascript" src="{% static 'js/simplemde.min.js' %}"></script>
<form method="POST" novalidate>
    {% csrf_token %} {{ form |crispy }}
    <button type="submit"class='action'>Create</button>
</form>

{%endblock content%} {% block scripts %}
<script>
    var simplemde = new SimpleMDE();
</script> {% endblock %}

dailyhunt/templates/buzz/see_video.html
{% extends "base.html" %}
{% block content %}
<!-- <video controls>
        <source src="{{video.video_url}}" />
</video> -->
<p>
    {{video.get_url }}
</p>
<iframe src="{{ video.video_url }}" height="350" width="350" ></iframe>
{% endblock %}

dailyhunt/templates/create_tag.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="POST" novalidate>
    {% csrf_token %}
    {{ form |crispy }}
    <button type="submit" class='action'>Add</button>
</form>

{%endblock content%}

dailyhunt/templates/index.html
{%extends 'base.html' %}
{% block content %}
<div class='row'>
<div class="card">
        <div class="card-body">
          <h4 class="card-title">News</h4>
          <p class="card-text">Manage your news articles</p>
          <a href="{% url 'news:create'%}" class="card-link">Add News</a>
          <a href="{% url 'news:browse'%}" class="card-link">Browse all News</a>
        </div>
      </div>
      <div class="card">
            <div class="card-body">
              <h4 class="card-title">Buzz</h4>
              <p class="card-text">Manage your videos.</p>
              <a href="{% url 'buzz:create'%}" class="card-link">Add Videos</a>
              <a href="{% url 'buzz:browse'%}" class="card-link">Browse all videos</a>
            </div>
          </div>
          <div class="card">
                <div class="card-body">
                  <h4 class="card-title">Tags</h4>
                  <p class="card-text">Manage tags</p>
                  <a href="{% url 'news:create_tag'%}" class="card-link">Add tags</a>
                  <a href="#" class="card-link">Browse all tags</a>
                </div>
              </div>
            </div>
{%endblock%}

dailyhunt/templates/news/browse_news.html
{% extends "base.html" %} 

{% block content %}
<h2>News</h6>
    <hr/>
<div class='row'>
<div class='col-md-3'>
    <ul class="list-group">
    {% for tag in tags %}
    <li class="list-group-item">
        {{tag.name}}
    </li>
    {%endfor%}
    </ul>
</div>
<div class='col-md-9'>
    {% for news_post in news %}
    <div class="newspost">
        <div class="thumbnail">
    
        </div>
        <div class="content">
            <div class="title">
                <a href="{% url 'news:see' news_post.id news_post.slugify %}">{{news_post.title}}</a>
            </div>
            <div class="subtitle">
                {{news_post.subtitle}}
            </div>
        </div>
    </div>
    {% endfor%} 
</div>
</div>
{% endblock content %}

dailyhunt/templates/news/create_news.html
{%extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/simplemde.min.css'  %}" />
<script type="text/javascript" src="{% static 'js/simplemde.min.js' %}"></script>
<form method="POST" novalidate>
    {% csrf_token %}
    {{ form |crispy }}
    <button type="submit" class='action'>Create</button>
</form>

{%endblock content%}
{% block scripts %}
<script>
    var simplemde = new SimpleMDE();
</script>
{% endblock %}

dailyhunt/templates/news/news_index.html
{% extends 'base.html' %} 

{% block content%}
<div class='row'>
        <div class='col-sm-2'>
                <ul class="list-group">
                        <li class="list-group-item"><a>News</a></li>
                        <li class="list-group-item">Buzz</li>
                        <li class="list-group-item">Tags</li>
                        <li class="list-group-item">Languages</li>
                      </ul>
            </div>
            <div class='col-sm-10'>
            </div>
</div>
{% endblock %}

dailyhunt/templates/news/see_article.html
{% extends "base.html" %} 
{%block content%}
<h3>
    {{news.title}}
</h3>
<h6>
    {{news.subtitle}}
</h6>
<div style="background-color:white;padding:5px">
    {{news.display}}
</div>
{%endblock%}